---
- name: Create Teku systemd service
  template:
    src: "{{ teku_systemd_template }}"
    dest: "{{ teku_systemd_dir }}/teku.service"
    owner: "root"
    group: "root"
  become: true
  when: ( teku_managed_service ) and
    ( ansible_os_family != "Darwin" )
  register: systemd_file

- name: Set updated optionally to trigger a systemd restart at the end
  set_fact:
    teku_state_updates: "{{ teku_state_updates + ['teku.systemd_file'] }}"
  when: systemd_file is changed

- name: Reload systemd to reread configs
  systemd:
    daemon_reload: yes
  become: true
  when: systemd_file is changed

- name: Enable and start Teku service
  systemd:
    name: teku
    state: "{{ teku_systemd_state }}"
    enabled: true
  become: true
  when: ( teku_state_updates|length > 0 ) and
    ( teku_managed_service ) and
    ( ansible_os_family != "Darwin" )

# Darwin only
- name: Create Launchd service plist for Darwin
  template:
    src: "{{ teku_launchd_template }}"
    dest: "{{ teku_launchd_dir }}/tech.pegasyseng.teku.plist"
  become: true
  when: ( ansible_os_family == "Darwin" ) and
    ( teku_managed_service )
